#!/bin/sh
set -eu
VERSION="0.2.0"
GSAPP_PATH=${GSAPP_PATH:-$HOME/.local/share/applications}

usage() {
  cat <<__USAGE__ >&2
usage: ${0##*/} <operation> [...]
manege local applications in GNOME Shell.

operations:
  ${0##*/} add <name> <command> [arg(s)]  # add a new application
  ${0##*/} edit <name>                    # edit a application
  ${0##*/} delete <name(s)>               # delete applications
  ${0##*/} list                           # list applications
  ${0##*/} help                           # show this help message
  ${0##*/} version                        # print the version
__USAGE__
}

gsapp_add() {
  if [ $# -lt 2 ]; then
    printf "%s\n" "usage: ${0##*/} add <name> <command> [args(s)]" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    printf "%s\n" "${0##*/} add: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    name=$1
    shift
    execute=$*
    application="$GSAPP_PATH/$name.desktop"
    if [ -f "$application" ]; then
      printf "%s\n" "${0##*/} add: \"$application\" has already exist" >&2
      exit 1
    fi
    cat <<__DESKTOP_FILE__ > "$application"
[Desktop Entry]
Name=$name
Exec=$execute
Type=Application
__DESKTOP_FILE__
  )
}

gsapp_edit() {
  if [ $# -lt 1 ]; then
    printf "%s\n" "usage: ${0##*/} gsapp <name>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    printf "%s\n" "${0##*/} edit: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    name=$1
    application="$GSAPP_PATH/$name.desktop"
    if [ ! -f "$application" ]; then
      printf "%s\n" "${0##*/} edit: \"$application\" doesn't exist" >&2
      exit 1
    fi
    ${EDITOR:-vi} "$application"
  )
}

gsapp_delete() {
  if [ $# -lt 1 ]; then
    printf "%s\n" "usage: ${0##*/} delete <name>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    printf "%s\n" "${0##*/} delete: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    for name in "$@"; do
      application="$GSAPP_PATH/$name.desktop"
      if [ ! -f "$application" ]; then
        printf "%s\n" "${0##*/} delete: \"$application\" doesn't exist" >&2
        exit 1
      fi
      rm -- "$application"
    done
  )
}

gsapp_list() {
  if [ ! -d "$GSAPP_PATH" ]; then
    exit 0
  fi
  for path in "$GSAPP_PATH"/*; do
    if [ "$path" = "${path%.desktop}" ]; then
      continue
    fi
    path=${path##*/}
    path=${path%.desktop}
    printf "%s\n" "$path"
  done
}

gsapp_help() {
  usage
}

gsapp_version() {
  printf "%s\n" "$VERSION" >&2
}

if [ $# -lt 1 ]; then
  usage
  exit 2
fi
operation=$1
shift
case $operation in
  add|edit|delete|list|help|version)
    "gsapp_$operation" "$@"
    exit 0
    ;;
  *)
    printf "%s\n" "${0##*/}: invalid operation '$operation'" >&2
    exit 2
    ;;
esac
