#!/bin/sh
set -eu
VERSION='0.1.0'
GSAPP_PATH="${GSAPP_PATH:-$HOME/.local/share/applications}"

usage() {
  cat <<__USAGE__ >&2
usage: ${0##*/} <operation> [...]
manege local applications in GNOME Shell.

operations:
  ${0##*/} add <name> <command> [arg(s)]  # add a new application
  ${0##*/} edit <name>                    # edit a application
  ${0##*/} delete <name(s)>               # delete applications
  ${0##*/} list                           # list applications
  ${0##*/} help                           # show this help message
  ${0##*/} version                        # print the version
__USAGE__
}

gsapp_add() {
  if [ $# -lt 2 ]; then
    echo "usage: ${0##*/} add <name> <command>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    echo "${0##*/} add: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    name="$1"
    shift
    execute="$*"
    application="$GSAPP_PATH/$name.desktop"
    if [ -f "$application" ]; then
      echo "${0##*/} add: \"$application\" has already exist" >&2
      exit 1
    fi
    cat <<__DESKTOP_FILE__ > "$application"
[Desktop Entry]
Name=$name
Exec=$execute
Type=Application
__DESKTOP_FILE__
  )
}

gsapp_edit() {
  if [ $# -lt 1 ]; then
    echo "usage: ${0##*/} gsapp <name>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    echo "${0##*/} edit: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    name="$1"
    application="$GSAPP_PATH/$name.desktop"
    if [ ! -f "$application" ]; then
      echo "${0##*/} edit: \"$application\" doesn't exist" >&2
      exit 1
    fi
    ${EDITOR:-vi} "$application"
  )
}

gsapp_delete() {
  if [ $# -lt 1 ]; then
    echo "usage: ${0##*/} delete <name>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    echo "${0##*/} delete: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    for name in "$@"; do
      application="$GSAPP_PATH/$name.desktop"
      if [ ! -f "$application" ]; then
        echo "${0##*/} delete: \"$application\" doesn't exist" >&2
        exit 1
      fi
      rm -- "$application"
    done
  )
}

gsapp_list() {
  if [ ! -d "$GSAPP_PATH" ]; then
    exit 0
  fi
  ls -- "$GSAPP_PATH" \
  | grep '.desktop$' \
  | sed 's/.desktop$//'
}

gsapp_help() {
  usage
}

gsapp_version() {
  echo "$VERSION" >&2
}

if [ $# -lt 1 ]; then
  usage
  exit 2
fi
operation="$1"
shift
case "$operation" in
  add|edit|delete|list|help|version)
    "gsapp_$operation" "$@"
    exit 0
    ;;
  *)
    echo "${0##*/}: invalid operation '$operation'" >&2
    exit 2
    ;;
esac
