#!/bin/sh
set -eu
GSAPP_PATH="${GSAPP_PATH:-$HOME/.local/share/applications}"

usage() {
  cat <<__USAGE__ >&2
usage: ${0##*/} <operation> [...]
operations:
  ${0##*/} add <name> <command>   # add a new application
  ${0##*/} delete <name>          # Delete the specified application
  ${0##*/} list                   # list applications
  ${0##*/} help                   # show this help message
__USAGE__
}

warn() {
  echo "${0##*/}: $*" >&2
}

operation_add() {
  if [ $# -lt 2 ]; then
    echo "usage: ${0##*/} add <name> <command>" >&2
    exit 2
  fi
  (
    name="$1"
    execute="$2"
    cat <<__DESKTOP_FILE__ > "$GSAPP_PATH/$name.desktop"
[Desktop Entry]
Name=$name
Exec=$execute
Type=Application
__DESKTOP_FILE__
  )
}

operation_list() {
  if [ ! -d "$GSAPP_PATH" ]; then
    exit 0
  fi
  ls -- "$GSAPP_PATH" \
  | grep '.desktop$' \
  | sed 's/.desktop$//'
}

operation_delete() {
  if [ $# -lt 1 ]; then
    echo "usage: ${0##*/} delete <name>" >&2
    exit 2
  fi
  if [ ! -d "$GSAPP_PATH" ]; then
    echo "${0##*/} delete: \"$GSAPP_PATH\" doesn't exist" >&2
    exit 2
  fi
  (
    name="$1"
    if [ ! -f "$GSAPP_PATH/$name.desktop" ]; then
      echo "${0##*/} delete: \"$GSAPP_PATH/$name\" doesn't exist" >&2
      exit 2
    fi
    rm -- "$GSAPP_PATH/$name.desktop"
  )
}

if [ $# -lt 1 ]; then
  usage
  exit 2
fi
operation="$1"
shift
case "$operation" in
  add)
    operation_add "$@"
    ;;
  delete)
    operation_delete "$@"
    ;;
  list)
    operation_list "$@"
    ;;
  help)
    usage
    exit 0
    ;;
  *)
    warn "invalid operation '$operation'"
    exit 2
    ;;
esac
